#!/bin/bash

# https://tinyurl.com/arch-gh-install
git clone --bare https://github.com/tserhii-gh/dotfiles.git $HOME/.dotfiles

dotfiles()
{
	dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"'
} 

dotfiles checkout
dotfiles config --local status.showUntrackedFiles no
