autoread: true
showread: false
feeds:
    - url: https://gitlab.archlinux.org/groups/archlinux/packaging/packages/-/issues.atom
      name: Arch Bugs
        #- url: https://eztv.li/ezrss.xml
        #name: EZTV
        #- url: https://www.limetorrents.lol/rss/16
        #name: LimeMovies
