# Disable softvol usage, and always use the system mixer if available.
# softvol=yes
volume=50

# cache settings
cache=yes
# Use 8MB input cache by default. The cache is enabled for network streams only.
# cache-default=8192
#
# Use 8MB input cache for everything, even local files.
# cache=auto
#
# If a seek is issued, and the target is 1024KB past the cached range, then
# keep reading until the seek target is hit, instead of doing a real seek.
# cache-seek-min=1024
#
# Disable the behavior that the player will pause if the cache goes below a
# certain fill size.
# cache-pause=yes
#
# Read ahead about 5 seconds of audio and video packets.
demuxer-seekable-cache=no
# demuxer-max-bytes=1000000
# demuxer-readahead-secs=5.0
# cache-file=/tmp/mpv-cache
# cache-file-size=16000
# cache-secs=5
#slang=en
screenshot-directory=/tmp
sub-auto=all
# audio-file-auto=fuzzy
no-sub
input-ipc-server=/tmp/mpvsocket
# osd-font-size=32
sub-codepage=utf8:cp1251
vo=gpu-next
ao=pipewire
hwdec=vaapi
vf-clr
geometry=30%:30%
autofit=640x480
ontop=yes
# ytdl-format='[width<=1920]'
# ytdl_path='yt-dlp'
# script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
# ytdl=no
# ytdl-format='bestvideo[height<=?1080]+bestaudio/best'
# ytdl-format='bestvideo[height<=?1080]+bestaudio/best'
#ytdl-format='(bv*+ba/b)[vcodec^=avc1][height<=1080]/ (bv*+ba/b)'
ytdl-format='(bv*[height=1080]+ba)[vcodec^=h264] / (bv*+ba/b)[height<=?1080]'
#ytdl-format='(bv*+ba/b)[height<=?1080][vcodec^=h264] / (bv*+ba)'
# ytdl-format='(bv*+ba/b)[height<=?480] / (bv*+ba)'
# ytdl-format='[height<=?1080]'
# ytdl-format="bestvideo[height<=?1080][vcodec!=vp9]+bestaudio/best"
